<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CDC2-D-519QS78" name="selenium.casestudy.NewTest1" tests="5" failures="1" timestamp="8 Jul 2019 04:55:34 GMT" time="42.854" errors="0">
  <testcase name="testPayment" time="8.745" classname="selenium.casestudy.NewTest1"/>
  <testcase name="testRegistration" time="12.469" classname="selenium.casestudy.NewTest1"/>
  <testcase name="testPayment1" time="14.632" classname="selenium.casestudy.NewTest1">
    <failure type="java.lang.AssertionError" message="expected [null] but found [[[ChromeDriver: chrome on XP (8c513995ca14d6b4b5d69422aa9923d5)] -&gt; name: transpwd]]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [[[ChromeDriver: chrome on XP (8c513995ca14d6b4b5d69422aa9923d5)] -> name: transpwd]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at org.testng.Assert.assertNull(Assert.java:434)
	at selenium.casestudy.NewTest1.testPayment1(NewTest1.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testPayment1 -->
  <testcase name="testCart" time="5.234" classname="selenium.casestudy.NewTest1"/>
  <testcase name="testLogin" time="1.774" classname="selenium.casestudy.NewTest1"/>
</testsuite> <!-- selenium.casestudy.NewTest1 -->
